title: Webman Docs
email: ddarkterminal@pm.me
description: >-
  webman is a high-performance HTTP service framework developed based on workerman.
  Webman is used to replace the traditional php-fpm architecture and provide ultra-high performance
  and scalable HTTP services. You can use webman to develop websites, you can also develop HTTP interfaces or microservices.
baseurl: "/"
url: ""
twitter_username: panggilmeiam
github_username:  darkterminal

# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/just-the-docs.png"

permalink: pretty
exclude: [
  "node_modules/",
  "*.gemspec",
  "*.gem",
  "Gemfile",
  "Gemfile.lock",
  "package.json",
  "package-lock.json",  "script/",
  "LICENSE.txt",
  "lib/",
  "bin/",
  "README.md",
  "Rakefile",
  "docs/tests/"
]

theme: "just-the-docs"
plugins:
  - jekyll-seo-tag

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Aux links for the upper right navigation
aux_links:
  "Webman on GitHub":
    - "//github.com/walkor/webman"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Documentaion &copy; 2022 Walkor. Distributed by an <a href=\"https://github.com/walkor/webman/tree/master/LICENSE\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/walkor/webman/docs" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme supports "light" (default) and "dark"
color_scheme: light
